### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by JeKuOrdina** [JeKuOrdina/SEBC#1]
Day 1: SEBC

**Comment by mfernest** [comment]
Assign an instructor once you are ready for review.

**Comment by cfusi** [comment]
The installation is complete, but I have a few remarks:

* The services `nscp` and `ntpd` are active but not enabled, so they will not start at reboot
<code>Loaded: loaded (/usr/lib/systemd/system/nscd.service; <b>disabled</b>; vendor preset: disabled)</code>
<code>Loaded: loaded (/usr/lib/systemd/system/ntpd.service; <b>disabled</b>; vendor preset: disabled)</code>

* Refer here to permanently disable Transparent Hugepages after reboot
https://www.cloudera.com/documentation/enterprise/5-9-x/topics/cdh_admin_performance.html

* Mysql replication seems compromised:
`Could not execute Write_rows event on table mysql.user; Duplicate entry 'localhost-root' for key 'PRIMARY', Error_code: 1062; handler error HA_ERR_FOUND_DUPP_KEY; the event's master log master1-bin.000001, end_log_pos 27368`

**Comment by JeKuOrdina** [comment]
Enabled ntpd and nscp with: with systemctl

**Comment by JeKuOrdina** [comment]
Refer here to permanently disable Transparent Hugepages after reboot was already modified in /etc/rc.d/rc.local.

**Comment by JeKuOrdina** [comment]
Could not execute Write_rows event on table mysql.user; Duplicate entry 'localhost-root' for key 'PRIMARY', Error_code: 1062; handler error HA_ERR_FOUND_DUPP_KEY; the event's master log master1-bin.000001, end_log_pos 27368

Will check later.

**Comment by JeKuOrdina** [comment]
Still an open issue

**Comment by JeKuOrdina** [comment]
> Mysql replication seems compromised:
Could not execute Write_rows event on table mysql.user; Duplicate entry 'localhost-root' for key 'PRIMARY', Error_code: 1062; handler error HA_ERR_FOUND_DUPP_KEY; the event's master log master1-bin.000001, end_log_pos 27368

Cause:

- Ran `setup_secure_mariadb.sh` on both master and slave server before starting up the replication. 
- Slave started replicating master from MASTER_LOG_POS=0 as I didn't provide the MASTER_LOG_POS at startup of the slave.

Solution:

- Don't run the `setup_secure_mariadb.sh` on the slave node.
- Add slave-skip-errors = 1062 [Duplicate entry], (It's ok, starting slave against a fresh master.)

![capture](https://user-images.githubusercontent.com/37252126/37458658-ff6174e6-2845-11e8-827d-3545a47e8d58.PNG)

**Comment by cfusi** [comment]
Lab is OK
